services:
  kp_db:
    image: postgres:latest
    container_name: kp_db
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: kp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - kp_db:/var/lib/postgresql/data

volumes:
  kp_db:

