services:
  wp_db:
    image: postgres:latest
    container_name: wp_db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: wp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - wp_db:/var/lib/postgresql/data

volumes:
  wp_db:

