services:
  kp_db:
    image: postgres:latest
    container_name: kp_db
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: kp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - kp_db:/var/lib/postgresql/data

  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "6433:5432"

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "9999:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres_keycloak
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    volumes:
      - ./keycloak/themes:/opt/bitnami/keycloak/themes/custom
      - ./keycloak/providers:/opt/bitnami/keycloak/providers
    depends_on:
      - postgres_keycloak


volumes:
  kp_db:
  keycloak_db_data:
