spring:
  datasource:
    url: jdbc:postgresql://localhost:7432/kp # 5432
    username: admin
    password: admin

  flyway:
    enabled: true

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:9999/realms/kita-realm}

server:
#  port: 8081